### PR TITLE
Kj 103 get movie event apicall

### PR DESCRIPTION
**Pull request by KristinJJ**
# Description
As a User, I want to be able to see a Ranking page populated with Event data using a lambda function.

Related to Issue #102 
Closes Issue #103 

# Tested
Chrome on MacOS

# Testing
- [ ] Click on Event button and Navigate to Ranking page from current Home page
- [ ] View that Event information has populated the ranking page (title, date, and movies)
- [ ] Enter a userID (verification to stop user from submitting a ranking without a userID to be addressed in a separate PR)
- [ ] Drag and drop the movies
- [ ] Click the submit button

### CODE REVIEW

**Review by ZenSorcere — COMMENTED** [review]
Combing over the code for this one--I knew you had made a new lambda for getting a specific movieEvent, based on what was done for getFinalRankings lambda. Examining the lambdas and the API Gateway routes:

- I noticed that line 105 in apicall.service.ts the http.get call for "GetMovieEvent" was still referencing `/getFinalRankings`.  I swapped in `/getMovieEvent` and it appears to work fine (as expected, since it's integrating a duplicate of the getFinalRankings Lambda function).

**Comment by ZenSorcere** [comment]
There are additional code changes in here around the final ranking resolve and the attempts at tallying rankings, which I don't believe are actually finalized yet--did you base this working branch off of a branch for Issued 91?

**Comment by KristinJJ** [comment]
> Combing over the code for this one--I knew you had made a new lambda for getting a specific movieEvent, based on what was done for getFinalRankings lambda. Examining the lambdas and the API Gateway routes:
> 
> * I noticed that line 105 in apicall.service.ts the http.get call for "GetMovieEvent" was still referencing `/getFinalRankings`.  I swapped in `/getMovieEvent` and it appears to work fine (as expected, since it's integrating a duplicate of the getFinalRankings Lambda function).

Good catch Mike! I have updated the getMovieEvent() in the apicall.service.ts to use /getMovieEvent instead of /getFinalRankings

**Comment by KristinJJ** [comment]
> There are additional code changes in here around the final ranking resolve and the attempts at tallying rankings, which I don't believe are actually finalized yet--did you base this working branch off of a branch for Issued 91?

Thanks for the review! I did base this branch off of the branch for Issue 91. Would you like me to either remove the unrelated code changes, or wait until the PR for Issue 91 is finished?

**Review by ZenSorcere — APPROVED** [review]
Line fixed, looks good, and ready for merging.

**Pull request merged**
